package com.pay.user.bean;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTurnover<M extends BaseTurnover<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTid(java.lang.Long tid) {
		set("tid", tid);
		return (M)this;
	}
	
	public java.lang.Long getTid() {
		return getLong("tid");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public M setNum(java.lang.Double num) {
		set("num", num);
		return (M)this;
	}
	
	public java.lang.Double getNum() {
		return getDouble("num");
	}

}
