package com.pay.user.bean;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

    public M setId(java.lang.Long id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.Long getId() {
        return getLong("id");
    }

    public M setFid(java.lang.Integer fid) {
        set("fid", fid);
        return (M) this;
    }

    public java.lang.Integer getFid() {
        return getInt("fid");
    }

    public M setName(java.lang.String name) {
        set("name", name);
        return (M) this;
    }

    public java.lang.String getName() {
        return getStr("name");
    }

    public M setUrl(java.lang.String url) {
        set("url", url);
        return (M) this;
    }

    public java.lang.String getUrl() {
        return getStr("url");
    }

    public M setContent(java.lang.String content) {
        set("content", content);
        return (M) this;
    }

    public java.lang.String getContent() {
        return getStr("content");
    }

}
