package com.pay.user.bean;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProportion<M extends BaseProportion<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCooperationId(java.lang.Long cooperationId) {
		set("cooperation_id", cooperationId);
		return (M)this;
	}
	
	public java.lang.Long getCooperationId() {
		return getLong("cooperation_id");
	}

	public M setMonth(java.util.Date month) {
		set("month", month);
		return (M)this;
	}
	
	public java.util.Date getMonth() {
		return get("month");
	}

	public M setMake(java.lang.Float make) {
		set("make", make);
		return (M)this;
	}
	
	public java.lang.Float getMake() {
		return getFloat("make");
	}

	public M setDesign(java.lang.Float design) {
		set("design", design);
		return (M)this;
	}
	
	public java.lang.Float getDesign() {
		return getFloat("design");
	}

}
