package com.pay.user.bean;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInvoice<M extends BaseInvoice<M>> extends Model<M> implements IBean {

    public M setId(java.lang.String id) {
        set("id", id);
        return (M) this;
    }

    public java.lang.String getId() {
        return getStr("id");
    }

    public M setCompanyId(java.lang.String companyId) {
        set("company_id", companyId);
        return (M) this;
    }

    public java.lang.String getCompanyId() {
        return getStr("company_id");
    }

    public M setServiceType(java.lang.String serviceType) {
        set("service_type", serviceType);
        return (M) this;
    }

    public java.lang.String getServiceType() {
        return getStr("service_type");
    }

    public M setName(java.lang.String name) {
        set("name", name);
        return (M) this;
    }

    public java.lang.String getName() {
        return getStr("name");
    }

    public M setTicketDate(java.util.Date ticketDate) {
        set("ticket_date", ticketDate);
        return (M) this;
    }

    public java.util.Date getTicketDate() {
        return get("ticket_date");
    }

    public M setTicketId(java.lang.String ticketId) {
        set("ticket_id", ticketId);
        return (M) this;
    }

    public java.lang.String getTicketId() {
        return getStr("ticket_id");
    }

    public M setTicketNum(java.lang.String ticketNum) {
        set("ticket_num", ticketNum);
        return (M) this;
    }

    public java.lang.String getTicketNum() {
        return getStr("ticket_num");
    }

    public M setBuyName(java.lang.String buyName) {
        set("buy_name", buyName);
        return (M) this;
    }

    public java.lang.String getBuyName() {
        return getStr("buy_name");
    }

    public M setGoodsName(java.lang.String goodsName) {
        set("goods_name", goodsName);
        return (M) this;
    }

    public java.lang.String getGoodsName() {
        return getStr("goods_name");
    }

    public M setCess(java.lang.String cess) {
        set("cess", cess);
        return (M) this;
    }

    public java.lang.String getCess() {
        return getStr("cess");
    }

    public M setCessTotal(java.lang.String cessTotal) {
        set("cess_total", cessTotal);
        return (M) this;
    }

    public java.lang.String getCessTotal() {
        return getStr("cess_total");
    }

    public M setBillMonth(java.lang.String billMonth) {
        set("bill_month", billMonth);
        return (M) this;
    }

    public java.lang.String getBillMonth() {
        return getStr("bill_month");
    }

    public M setBillDate(java.util.Date billDate) {
        set("bill_date", billDate);
        return (M) this;
    }

    public java.util.Date getBillDate() {
        return get("bill_date");
    }

    public M setCessMoney(java.lang.String cessMoney) {
        set("cess_money", cessMoney);
        return (M) this;
    }

    public java.lang.String getCessMoney() {
        return getStr("cess_money");
    }

    public M setDate(java.util.Date date) {
        set("date", date);
        return (M) this;
    }

    public java.util.Date getDate() {
        return get("date");
    }

    public M setInvoiceType(java.lang.String invoiceType) {
        set("invoice_type", invoiceType);
        return (M) this;
    }

    public java.lang.String getInvoiceType() {
        return getStr("invoice_type");
    }

}
