package com.pay.user.bean;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInvoice<M extends BaseInvoice<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}
	
	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

	public M setServiceType(java.lang.String serviceType) {
		set("service_type", serviceType);
		return (M)this;
	}
	
	public java.lang.String getServiceType() {
		return getStr("service_type");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTicketDate(java.util.Date ticketDate) {
		set("ticket_date", ticketDate);
		return (M)this;
	}
	
	public java.util.Date getTicketDate() {
		return get("ticket_date");
	}

	public M setTicketType(java.lang.String ticketType) {
		set("ticket_type", ticketType);
		return (M)this;
	}
	
	public java.lang.String getTicketType() {
		return getStr("ticket_type");
	}

	public M setTicketId(java.lang.String ticketId) {
		set("ticket_id", ticketId);
		return (M)this;
	}
	
	public java.lang.String getTicketId() {
		return getStr("ticket_id");
	}

	public M setTicketNum(java.lang.String ticketNum) {
		set("ticket_num", ticketNum);
		return (M)this;
	}
	
	public java.lang.String getTicketNum() {
		return getStr("ticket_num");
	}

	public M setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}
	
	public java.lang.String getGoodsName() {
		return getStr("goods_name");
	}

	public M setCess(java.lang.Float cess) {
		set("cess", cess);
		return (M)this;
	}
	
	public java.lang.Float getCess() {
		return getFloat("cess");
	}

	public M setCessTotal(java.lang.Float cessTotal) {
		set("cess_total", cessTotal);
		return (M)this;
	}
	
	public java.lang.Float getCessTotal() {
		return getFloat("cess_total");
	}

	public M setBillMonth(java.util.Date billMonth) {
		set("bill_month", billMonth);
		return (M)this;
	}
	
	public java.util.Date getBillMonth() {
		return get("bill_month");
	}

	public M setBillDate(java.util.Date billDate) {
		set("bill_date", billDate);
		return (M)this;
	}
	
	public java.util.Date getBillDate() {
		return get("bill_date");
	}

	public M setCessMoney(java.lang.String cessMoney) {
		set("cess_money", cessMoney);
		return (M)this;
	}
	
	public java.lang.String getCessMoney() {
		return getStr("cess_money");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public M setInvoiceType(java.lang.Boolean invoiceType) {
		set("invoice_type", invoiceType);
		return (M)this;
	}
	
	public java.lang.Boolean getInvoiceType() {
		return get("invoice_type");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}

}
