package com.pay.user.bean;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTheme<M extends BaseTheme<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setDesignId(java.lang.String designId) {
		set("design_id", designId);
		return (M)this;
	}
	
	public java.lang.String getDesignId() {
		return getStr("design_id");
	}

	public M setMakeId(java.lang.String makeId) {
		set("make_id", makeId);
		return (M)this;
	}
	
	public java.lang.String getMakeId() {
		return getStr("make_id");
	}

	public M setServiceType(java.lang.String serviceType) {
		set("service_type", serviceType);
		return (M)this;
	}
	
	public java.lang.String getServiceType() {
		return getStr("service_type");
	}

	public M setCompanyId(java.lang.Long companyId) {
		set("company_id", companyId);
		return (M)this;
	}
	
	public java.lang.Long getCompanyId() {
		return getLong("company_id");
	}

	public M setCooperationId(java.lang.Long cooperationId) {
		set("cooperation_id", cooperationId);
		return (M)this;
	}
	
	public java.lang.Long getCooperationId() {
		return getLong("cooperation_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setEname(java.lang.String ename) {
		set("ename", ename);
		return (M)this;
	}
	
	public java.lang.String getEname() {
		return getStr("ename");
	}

	public M setShelvesDate(java.util.Date shelvesDate) {
		set("shelves_date", shelvesDate);
		return (M)this;
	}
	
	public java.util.Date getShelvesDate() {
		return get("shelves_date");
	}

	public M setMoneyType(java.lang.Integer moneyType) {
		set("money_type", moneyType);
		return (M)this;
	}
	
	public java.lang.Integer getMoneyType() {
		return getInt("money_type");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

}
