package com.pay.user.bean;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseScale<M extends BaseScale<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setCooperationId(java.lang.Long cooperationId) {
		set("cooperation_id", cooperationId);
		return (M)this;
	}
	
	public java.lang.Long getCooperationId() {
		return getLong("cooperation_id");
	}

	public M setMonth(java.util.Date month) {
		set("month", month);
		return (M)this;
	}
	
	public java.util.Date getMonth() {
		return get("month");
	}

	public M setUserId(java.lang.String userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	public M setPay(java.lang.Double pay) {
		set("pay", pay);
		return (M)this;
	}
	
	public java.lang.Double getPay() {
		return getDouble("pay");
	}

	public M setRatio(java.lang.Double ratio) {
		set("ratio", ratio);
		return (M)this;
	}
	
	public java.lang.Double getRatio() {
		return getDouble("ratio");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

}
