package com.pay.user.model;

import com.pay.user.bean.BaseArchives;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Archives extends BaseArchives<Archives> {
	public static final Archives dao = new Archives().dao();
}
