package com.pay.user.model;

import com.pay.user.bean.BaseCausation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Causation extends BaseCausation<Causation> {
	public static final Causation dao = new Causation().dao();
}
