package com.pay.user.model;

import com.pay.user.bean.BaseCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Company extends BaseCompany<Company> {
    public static final Company dao = new Company().dao();
}
