package com.pay.user.model;

import com.pay.user.bean.BaseContract;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contract extends BaseContract<Contract> {
    public static final Contract dao = new Contract().dao();
}
