package com.pay.user.model;

import com.pay.user.bean.BaseCooperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Cooperation extends BaseCooperation<Cooperation> {
    public static final Cooperation dao = new Cooperation().dao();
}
