package com.pay.user.model;

import com.pay.user.bean.BaseEducation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Education extends BaseEducation<Education> {
    public static final Education dao = new Education().dao();
}
