package com.pay.user.model;

import com.pay.user.bean.BaseEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Equipment extends BaseEquipment<Equipment> {
    public static final Equipment dao = new Equipment().dao();
}
