package com.pay.user.model;

import com.pay.user.bean.BaseExperience;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Experience extends BaseExperience<Experience> {
    public static final Experience dao = new Experience().dao();
}
