package com.pay.user.model;

import com.pay.user.bean.BaseFillturnover;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fillturnover extends BaseFillturnover<Fillturnover> {
	public static final Fillturnover dao = new Fillturnover().dao();
}
