package com.pay.user.model;

import com.pay.user.bean.BaseInvoice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Invoice extends BaseInvoice<Invoice> {
    public static final Invoice dao = new Invoice().dao();
}
