package com.pay.user.model;

import com.pay.user.bean.BaseMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menu extends BaseMenu<Menu> {
    public static final Menu dao = new Menu().dao();
}
