package com.pay.user.model;

import com.pay.user.bean.BaseMoney;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Money extends BaseMoney<Money> {
    public static final Money dao = new Money().dao();
}
