package com.pay.user.model;

import com.pay.user.bean.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
    public static final Permission dao = new Permission().dao();
}
