package com.pay.user.model;

import com.pay.user.bean.BaseProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Project extends BaseProject<Project> {
    public static final Project dao = new Project().dao();
}
