package com.pay.user.model;

import com.pay.user.bean.BaseProportion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Proportion extends BaseProportion<Proportion> {
	public static final Proportion dao = new Proportion().dao();
}
