package com.pay.user.model;

import com.pay.user.bean.BasePunish;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Punish extends BasePunish<Punish> {
    public static final Punish dao = new Punish().dao();
}
