package com.pay.user.model;

import com.pay.user.bean.BaseRolePermission;
import lombok.ToString;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@ToString
public class RolePermission extends BaseRolePermission<RolePermission> {
    public static final RolePermission dao = new RolePermission().dao();

    @Override
    public int hashCode() {
        return getRoleId().hashCode() + getPermissionId().hashCode();
    }

}
