package com.pay.user.model;

import com.pay.user.bean.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
    public static final Role dao = new Role().dao();
}
