package com.pay.user.model;

import com.pay.user.bean.BaseScale;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Scale extends BaseScale<Scale> {
	public static final Scale dao = new Scale().dao();
}
