package com.pay.user.model;

import com.pay.user.bean.BaseTheme;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Theme extends BaseTheme<Theme> {
    public static final Theme dao = new Theme().dao();
}
