package com.pay.user.model;

import com.pay.user.bean.BaseTurnover;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Turnover extends BaseTurnover<Turnover> {
	public static final Turnover dao = new Turnover().dao();
}
