package com.pay.user.model;

import com.pay.user.bean.BaseUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfo extends BaseUserInfo<UserInfo> {
    public static final UserInfo dao = new UserInfo().dao();
}
