package com.pay.user.model;

import com.pay.user.bean.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User().dao();


}
