package com.pay.user.model;

import com.pay.user.bean.BaseWork;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Work extends BaseWork<Work> {
    public static final Work dao = new Work().dao();
}
